In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf
plt.style.use('ggplot')
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
path = '/content/drive/MyDrive/Dataset/sp500_companies.csv'
df = pd.read_csv(path)
df.shape

(493, 16)

In [ ]:
# Dropping less useful columns
df = df[['Exchange', 'Symbol',
    #'Shortname',
    'Longname',
    #'Sector',
    'Industry',
       'Currentprice', 'Marketcap',
    #'Ebitda',
    'Revenuegrowth',
    #'City',
    'State',
    'Country',
    #'Fulltimeemployees', 'Longbusinesssummary',
    'Weight']]

In [ ]:
df.shape

(493, 10)

In [ ]:
df.describe()

       Currentprice     Marketcap  Revenuegrowth      Weight
count    493.000000  4.930000e+02     492.000000  493.000000
mean     162.398884  6.423573e+10       0.528150    0.002028
std      262.710729  1.588148e+11       3.837191    0.005015
min        8.500000  4.060800e+09      -0.454000    0.000128
25%       58.250000  1.599014e+10       0.047000    0.000505
50%      102.500000  2.882696e+10       0.113000    0.000910
75%      193.070000  6.070308e+10       0.221250    0.001917
max     4360.020000  2.487210e+12      61.423000    0.078540

In [ ]:
df.Marketcap = df.Marketcap.astype(int)
df.dtypes

Exchange          object
Symbol            object
Longname          object
Industry          object
Currentprice     float64
Marketcap          int64
Revenuegrowth    float64
State             object
Country           object
Weight           float64
dtype: object

In [ ]:
df.isna().sum()

Exchange          0
Symbol            0
Longname          0
Industry          0
Currentprice      0
Marketcap         0
Revenuegrowth     1
State            19
Country           0
Weight            0
dtype: int64

In [ ]:
df.loc[df.duplicated()]

Empty DataFrame
Columns: [Exchange, Symbol, Longname, Industry, Currentprice, Marketcap, Revenuegrowth, State, Country, Weight]
Index: []

In [ ]:
df.loc[df.duplicated(subset=['Symbol'])]

Empty DataFrame
Columns: [Exchange, Symbol, Longname, Industry, Currentprice, Marketcap, Revenuegrowth, State, Country, Weight]
Index: []

In [ ]:
df.query